# largely based on https://jam.dev/blog/automating-chrome-extension-publishing/
# learn more: https://docs.github.com/en/actions

name: Stage Chrome Web Store Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-artifact:
    name: Build Chrome Extension Artifact ğŸ—ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ”
        uses: actions/checkout@v3

      - name: Setup Node.js ğŸ› ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm â¬‡ï¸
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Store pnpm cache directory ğŸ’¿
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache dependencies ğŸ—„ï¸
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies ğŸ“¦
        run: pnpm install

      - name: Build ğŸ”¨
        run: pnpm build

      - name: Zip ğŸ—œï¸
        run: zip -r -FS extension-${{ github.event.pull_request.head.sha }}.zip dist

      - name: Upload Artifact ğŸ“¤
        uses: actions/upload-artifact@v3
        with:
          name: extension-${{ github.sha }}
          path: extension-${{ github.event.pull_request.head.sha }}.zip

  # reference:
  # * https://developer.chrome.com/docs/webstore/using_webstore_api/
  # * https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md
  stage-extension:
    name: Stage Chrome Extension on the Chrome Web Store ğŸš€
    runs-on: ubuntu-latest
    needs: build-artifact
    env:
      CRX_EXTENSION_ID: deibnakcmchjdngfblcckddhhcnghocd

    steps:
      - name: Setup Node.js ğŸ› ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get artifact ğŸ“¥
        uses: actions/download-artifact@v3
        with:
          name: extension-${{ github.sha }}

      - name: Install chrome-webstore-upload-cli â¬‡ï¸
        run: npm install -g chrome-webstore-upload-cli

      - name: Upload to web store ğŸš€
        run: |
          chrome-webstore-upload-cli upload \
            --source extension-${{ github.sha }}.zip \
            --extension-id ${{ env.CRX_EXTENSION_ID }} \
            --client-id ${{ secrets.CRX_CLIENT_ID }} \
            --client-secret ${{ secrets.CRX_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CRX_REFRESH_TOKEN }}
